BUNDLE_NAME = FinnPreferences

$(BUNDLE_NAME)_FILES          = FinnRootListController.m
$(BUNDLE_NAME)_CFLAGS         = -fobjc-arc
$(BUNDLE_NAME)_FRAMEWORKS     = UIKit Preferences
$(BUNDLE_NAME)_INSTALL_PATH   = /Library/PreferenceBundles
$(BUNDLE_NAME)_RESOURCE_DIRS  = Resources

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
