TWEAK_NAME = Finn

$(TWEAK_NAME)_FILES     = Finn.x
$(TWEAK_NAME)_CFLAGS    = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
$(TWEAK_NAME)_FRAMEWORKS = UIKit QuartzCore

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
