include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DockLibraryPrefs

DockLibraryPrefs_FILES = DLRootListController.m
DockLibraryPrefs_INSTALL_PATH = /Library/PreferenceBundles
DockLibraryPrefs_FRAMEWORKS = UIKit
DockLibraryPrefs_PRIVATE_FRAMEWORKS = Preferences
DockLibraryPrefs_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/bundle.mk
