ARCHS = arm64 arm64e
TARGET = iphone:clang:16.5:15.0
THEOS_PACKAGE_SCHEME = rootless

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ReSettings

ReSettings_FILES = Tweak.xm SCCSectionHeaderView.m SCCommon.m
ReSettings_FRAMEWORKS = UIKit QuartzCore CoreFoundation
ReSettings_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk

SUBPROJECTS += prefs
include $(THEOS_MAKE_PATH)/aggregate.mk
